### ISSUE TITLE
Bug: Cannot resolve native dependencies in `app/package.json`

### ISSUE THREAD

**Issue by anthonyraymond** [chentsulin/electron-react-boilerplate#933] opened 2017-04-21 08:16 UTC
Hi,

Since last release (0.11.0), i can't import modules declared in `app/package.json`. I changed nothing, and it was working on [this commit](https://github.com/chentsulin/electron-react-boilerplate/commit/2b0f7606bb06397e87078bb4f00c357efc778e65)

It results in the following error
```
Uncaught Error: Cannot find module 'electron-config'
    at Module._resolveFilename (module.js:470)
    at Function.Module._resolveFilename (T:\ProjetsAutre\archive-notifier\node_modules\electron\dist\resources\electron.asar\common\reset-se…:35)
    at Function.Module._load (module.js:418)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at Object.49 (external "electron-config":1)
    at __webpack_require__ (bootstrap 6b881ca…:657)
    at fn (bootstrap 6b881ca…:85)
    at Object../app/actions/settings.js (settings.js:2)
    at __webpack_require__ (bootstrap 6b881ca…:657)
```

In this case it's *electron-config*, but i tryed with differents modules. electron-config is installed with yarn.

`app/package.json`
```
{
  ...
  "scripts": {
    "postinstall": "npm rebuild --runtime=electron --target=1.6.1 --disturl=https://atom.io/download/atom-shell --build-from-source"
  },
  "license": "MIT",
  "dependencies": {
    "chokidar": "^1.6.1",
    "electron-config": "^0.2.1",
    "node-notifier": "^5.1.2",
    "node-yaml": "^3.0.3"
  }
}
```

### How to reproduce

1. Clone the project.
2. `app/package.josn`
```
"dependencies": {
  "node-yaml": "^3.0.3"
}
```

3. `app/index.js`
```
import yaml from 'node-yaml';
```
4. `yarn install`
5. `npm run dev`

**Comment by amilajack** [comment] 2017-04-21 13:22
Interesting. I'll look into this. Thanks for reporting!

**Comment by amilajack** [comment] 2017-04-21 14:17
```bash
git clone https://github.com/chentsulin/electron-react-boilerplate.git foo
cd foo
yarn
cd app && yarn add --dev node-yaml && cd ..
# updated ./app/index.js to import 'node-yaml'
yarn build # no errors
yarn dev # Throws
```

```
Uncaught TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (index.js:24)
    at Object../app/node_modules/node-yaml/index.js (index.js:275)
    at __webpack_require__ (bootstrap 2c05b86…:657)
    at fn (bootstrap 2c05b86…:85)
    at Object../app/index.js (index.js:6)
    at __webpack_require__ (bootstrap 2c05b86…:657)
    at fn (bootstrap 2c05b86…:85)
    at Object.26 (bundle.js:40227)
    at __webpack_require__ (bootstrap 2c05b86…:657)
    at module.exports../app/actions/counter.js.Object.defineProperty.value (bootstrap 2c05b86…:706)
```

**Comment by anthonyraymond** [comment] 2017-04-21 14:28
Hi don't know if this is related or not, but i added node-yaml as a `dependcies` not `devDependencies`, i never understood the difference anyway...
But the error you do report also happen when adding node-yaml in `/package.json` instead of `app/package.json`.

My first tought was that it wasn't exported as ` externals` in webpack config, but `externals: Object.keys(externals || {})` do his job properly in `webpack.config.base.js`.

It may be because of it fail to resolve `filename` and don't expose the module... But i can't understand what has changed.

**Comment by amilajack** [comment] 2017-04-21 14:36
See these issues:

https://github.com/sindresorhus/electron-config/issues/9
https://github.com/yargs/yargs/issues/390

Seems to be related to webpack

**Comment by Slapbox** [comment] 2017-04-21 15:40
Seeing the same issue with `electron-notifications` package.

**Comment by Slapbox** [comment] 2017-04-21 16:21
It seems worth mentioning that the only package I am seeing this error for (though perhaps there would be more to follow if this was not a show-stopper) is for the only package I am loading in my top level `package.json` and my `app\package.json`

**Comment by Slapbox** [comment] 2017-04-21 16:41
Removing from my `app\package.json` only resolved the issue, though I know it will not build this way.

**Comment by amilajack** [comment] 2017-04-21 17:34
What happens if you remove it from your `./package.json`?

**Comment by Slapbox** [comment] 2017-04-21 17:42
I haven't tried it in this build, but previous experience tells me it will not build without it being in the top level `package.json`

**Comment by Slapbox** [comment] 2017-04-21 17:56
Builds, but yields an identical error.

**Comment by amilajack** [comment] 2017-04-22 17:47
I found that https://github.com/chentsulin/electron-react-boilerplate/pull/921/commits/f36e9d26791d2c2389187cbdb9647f7335578516 is the cause of this. Will investigate further today

**Comment by amilajack** [comment] 2017-04-22 19:10
I fixed this in the `dev-master` branch. Would be great if everyone here could test this

**Comment by Slapbox** [comment] 2017-04-22 19:34
Will do as soon as I can! Thanks for your hard work as always @amilajack

**Comment by anthonyraymond** [comment] 2017-04-22 19:35
I try it in a few seconds

**Comment by anthonyraymond** [comment] 2017-04-22 19:48
Now having this error on `npm run dev`
![image](https://cloud.githubusercontent.com/assets/7503585/25307681/46b35aaa-27a5-11e7-9feb-ad37a283ac6e.png)

**Comment by anthonyraymond** [comment] 2017-04-22 19:54
Hum... i don't know what is `vendor.dll.js` actualy, but i suposed it wasn't meant to be HTML right?

![image](https://cloud.githubusercontent.com/assets/7503585/25307731/466059d0-27a6-11e7-8531-f57c9e647d80.png)

**Comment by amilajack** [comment] 2017-04-22 22:25
@anthonyraymond my bad. I accidentally merged dev-master with master and that overrode the reverts that I made to dev-master. It should work this time

**Comment by Djiit** [comment] 2017-04-23 08:26
Just tested it in dev-master, works great

**Comment by anthonyraymond** [comment] 2017-04-23 14:08
Everything seems to work fine :)
Thanks !

**Comment by amilajack** [comment] 2017-04-23 15:33
🎉 🎉 🎉

**Closed by amilajack** 2017-04-23 15:33 UTC
Labels: bug

**Comment by rahmatkruniawan** [comment] 2017-04-23 21:42
@amilajack  after got error 

> vendor.dll.js
what I have to do ?  I still got same problem. 
If work correctly please update the master, so we can use this boilerplate + sqlite ^^

**Comment by amilajack** [comment] 2017-04-23 22:00
@rahmatkruniawan [made this repo](https://github.com/amilajack/erb-sqlite-example) as an example just for you. It demos using sqlite3 with electron-react-boilerlate. Enjoy!
