### ISSUE TITLE
eslint import error

### ISSUE THREAD

**Issue by hemedani** [chentsulin/electron-react-boilerplate#1195] opened 2017-09-04 16:54 UTC
eslint trow error for import every package listed in app/package.json but it's not listed in root/package.json
```
[eslint] 'react' should be listed in the project's dependencies. Run 'npm i -S react' to add it (import/no-extraneous-dependencies)
```

**Comment by uppe-r** [comment] 2017-10-03 14:15
I can't reproduce this with the boilerplate. Are you sure you're on the latest boilerplate release?

**Comment by hemedani** [comment] 2017-10-05 20:44
No I'm in a old release because of my project
How can i solve this error

**Comment by uppe-r** [comment] 2017-10-05 21:31
Maybe try checking the last commit made by the maintainers when you cloned the boilerplate and see if the commits done after have something to do with your issue?

**Comment by amilajack** [comment] 2017-10-16 02:08
Not enough information to debug this. Closing until more information is provided

**Closed by amilajack** 2017-10-16 02:08 UTC
