### ISSUE TITLE
Stops on "Starting Main process.."

### ISSUE THREAD

**Issue by giorgi-m** [chentsulin/electron-react-boilerplate#1635] opened 2018-07-14 19:17 UTC
I had no issue to run/build my app, until I had to kill it from taskmanager.
After this, when I try to:

> npm run dev

The terminal "hangs" at this point:

> 
> Starting Main Process...
> 
> electron-react-boilerplate@0.13.3 start-main-dev C:\Projects\pair-matching
> cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js

I restarted PC, didn't help.

**Comment by goldylucks** [comment] 2018-07-14 20:40
@giorgi-m try cloning the repo to another folder, and see if it continues.

If it does, the problem is in your machine.
If it doesn't, the problem is in your code.

So we will know how to continue debugging this.

**Comment by giorgi-m** [comment] 2018-07-14 21:15
@goldylucks it was a toy project I removed it, but:
unlikely problem was in code because it was working fine, it started to do this, after I killed the app from taskmanager. 

If I encounter this next time, I will post and then we can try to debug.

**Comment by goldylucks** [comment] 2018-07-15 09:38
so you can close this for now @giorgi-m ?

**Closed** 2018-07-15 14:04 UTC
