### ISSUE TITLE
Package for windows shows a blank screen.

### ISSUE THREAD

**Issue by hyalkaf** [chentsulin/electron-react-boilerplate#344] opened 2016-08-17 23:03 UTC
I ran npm run package and It worked fine with no errors. When I open the app it shows a blank screen. I opened devtools in production mode so I see what is going on and here are the error messages in the console:

file:///C:/blah/release/win32-x64/Port%20Analyzer-win32-x64/resources/app/dist/style.css Failed to load resource: net::ERR_FILE_NOT_FOUND

bundle.js:1 Uncaught Error: Cannot find module "../node_modules/toastr/build/toastr.min.css"

What am I doing wrong?

**Comment by amilajack** [comment] 2016-08-17 23:06
Did you do a fresh clone or did you clone and make modifications?

**Comment by hyalkaf** [comment] 2016-08-18 16:02
I made a clone and made some modifications

**Comment by amilajack** [comment] 2016-08-18 16:09
Did it work before you modified it?

**Comment by hyalkaf** [comment] 2016-08-18 16:13
I didn't try to package it before. This is my first time doing it. You are probably correct that I have to examine where it looks for files. Is there a guide on how the whole setup works so that I can edit it?

**Comment by amilajack** [comment] 2016-08-18 16:21
try reforking the project, reinstalling everything, and then npm run package

**Comment by amilajack** [comment] 2016-08-18 16:21
Also what are your node and npm versions?

**Comment by hyalkaf** [comment] 2016-08-18 16:33
Forked the project and npm installing now to see if it works. The project I'm working on is private so I have another repo. I have node v4.4.7 and npm v2.15.8

**Comment by amilajack** [comment] 2016-08-18 16:39
I would recommend using node `6.4.0` and the latest npm version. Those are what I use and I haven't gotten any errors when using them.

**Comment by hyalkaf** [comment] 2016-08-18 16:41
Ok I will update npm and node then and see what happens. Thanks a lot.

**Comment by hyalkaf** [comment] 2016-08-18 17:44
I updated npm and node but no luck. I guess I made modification that the paths fails to find correct files. One thing is importing css files from node_modules which I guess is different that what the boilerplate is doing.

**Comment by amilajack** [comment] 2016-08-18 17:49
try this, assuming that you are running a fresh clone without any modifications:

```
rm -rf node_modules
npm cache clean
npm i
npm rb
npm run package
```

**Comment by hyalkaf** [comment] 2016-08-18 18:17
The fresh copy is working fine. It's the modified one that is still not working even after updating node and npm.

**Comment by amilajack** [comment] 2016-08-18 18:32
They i dont think i can be of much help. You shouldn't open an issue here if there isn't a problem with this project.

**Comment by amilajack** [comment] 2016-08-18 19:19
Can you send a link to the source?

**Comment by hyalkaf** [comment] 2016-08-18 19:24
You are correct I guess. Thanks for the help though. I don't think I can share the source code.

**Comment by hyalkaf** [comment] 2016-08-18 19:26
I guess I wanted more of where I can know more about how this boilerplate is doing packaging so that I can edit those files to whatever I have changed.

**Comment by amilajack** [comment] 2016-08-18 19:29
The packaging logic is done in package.js. If you want to debug in production, try commenting https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.development.js#L19 and https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.development.js#L32

**Comment by hyalkaf** [comment] 2016-08-18 20:24
Thanks a lot. I will look into it

**Comment by Slapbox** [comment] 2016-09-07 16:32
Unfortunately I ran into the same issue. I initially had removed React-Router for my app, but added it back thinking perhaps this was related to how I broke it. When commenting out the two lines above, the package builds fine but no window appears at all when the EXE is loaded now. Any thoughts? 

I can't think of anything I might be doing that would break it in production and not in development.

**Comment by amilajack** [comment] 2016-09-07 17:16
@hyalkaf what is the state of this? Did you fix the problem? If you did, please close this.

**Comment by Slapbox** [comment] 2016-09-07 18:28
This problem is not resolved, at least for me, and while it is due to
modifications to the code, the modifications should be expected as this is
a boilerplate.

Without better documentation as to why this happens or a code fix for this
the boilerplate aspect of this project is really moot. Code changes that
comply with all the original methods in the boilerplate and differing in
the specific code called via the same methods should not break the project.

It's a really great project. I'd love to see it work as intended.

**Comment by amilajack** [comment] 2016-09-07 19:59
Did you try commenting the lines?

**Comment by Slapbox** [comment] 2016-09-07 20:14
It works as intended as a demonstration piece. I wouldn't call it a working boilerplate if you can't change code in the App folder without breaking the whole thing even when you carefully redesign your app to work within the original confines of the boilerplate.

I did comment the two lines out and repackaged it, however it doesn't launch a window at all at that point. Instead it just opens processes in the background when launched. I will continue investigating, but this does seem to be a substantial issue with the boilerplate if no one can explain how to use it in such a way this does not occur. My app works 100% perfectly in dev, 0% in production package.

**Comment by Slapbox** [comment] 2016-09-07 20:55
Additionally just ruled out Windows file name length limits. The node_modules folder in /release/ had some names that approached the limit, but moving to a shorter file path didn't help.

**Comment by Slapbox** [comment] 2016-09-07 21:14
Haven't found the root of my issue yet, but I have debugging tools on the packaged app now so it's only a matter of time. For posterity, you want to set the 'false' on line 39 to 'true'

https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.development.js#L39

**Comment by amilajack** [comment] 2016-09-20 04:53
@Slapbox did you resolve the issue?

**Comment by tlackemann** [comment] 2016-10-03 15:56
@Slapbox fwiw I also had a lot of troubles with a blank window (on macOS) however I was able to resolve by enabling this block for production https://github.com/chentsulin/electron-react-boilerplate/blob/master/main.development.js#L55-L67

The issue was something in my react code for some reason, scratching my head too as to why it worked in dev but I think that's because I'm very new to webpack and don't understand the full pipeline.

Anyway, hope it helps some! Thanks for creating such a great boilerplate folks!

**Comment by amilajack** [comment] 2016-10-03 17:33
Closing due to no response from @Slapbox

**Closed** 2016-10-03 17:32 UTC
Labels: waiting-for-response

**Comment by Slapbox** [comment] 2016-10-04 03:09
Yes I did resolve it, but this is a very likely issue to come up again and again without better documentation. Great boilerplate once you figure everything out for yourself though.

**Comment by amilajack** [comment] 2016-10-04 05:02
Do you remember what the issue was?

**Comment by musyilmaz** [comment] 2017-04-26 13:26
Hello there,

I currently have a similar issue. Developing on mac and trying to package it to windows. My setup also utilizes mongodb with spawn from child_process. I can easily run on development env and when I package for darwin env. But I have blank white screen for the case of windows. 

I tried to followup the fixes on this issue but cant figure out the line locations :(

**Comment by Slapbox** [comment] 2017-04-26 15:21
@musyilmaz if you run `DEBUG_PROD=true npm run start`

What errors does it show in console if any?

**Comment by musyilmaz** [comment] 2017-04-26 15:23
That is DEBUG_PROD=true npm run package-win right?

if so that is not activating the devtools for me :(

**Comment by amilajack** [comment] 2017-04-26 15:24
`DEBUG_PROD=true npm run package` should work if you have `v0.10.1`

**Comment by Slapbox** [comment] 2017-04-26 15:26
@musyilmaz do you get any errors or warnings in your terminal when you run either the command amilajack mentioned?

@amilajack, can you clarify for me, `DEBUG_PROD=true npm run start` is essentially the same thing except it won't package it into any `exe` files, is that right?

**Comment by musyilmaz** [comment] 2017-04-26 15:27
I was using a fork of the repo from like 2 months ago, with a hugely modified main process with express backend server and mongodb requirements. 

I will try to make them work on the new repo today or tomorrow :( Not sure how but I will :)

**Comment by musyilmaz** [comment] 2017-04-26 15:29
Ok, I run the nom run start with debug options and the application fired in mac but got an error of this in terminal[](url)
![screen shot 2017-04-26 at 18 28 20](https://cloud.githubusercontent.com/assets/7712706/25442663/49595226-2aae-11e7-8e7e-ff850d4744a8.png)

**Comment by amilajack** [comment] 2017-04-26 15:29
@musyilmaz I'm going to add a `UPGRADE.md` guide which will have instructions for upgrading to newer versions of the boilerplate. Ideally, it will be [similar to what laravel has](https://laravel.com/docs/5.3/upgrade).

**Comment by amilajack** [comment] 2017-04-26 15:30
> I was using a fork of the repo from like 2 months ago

In this case, you are not on `v0.10.1`. Your package.json should say `v0.10.0`. You have to perform the upgrade first

**Comment by musyilmaz** [comment] 2017-04-26 15:31
@amilajack You are the best :)

**Comment by Slapbox** [comment] 2017-04-26 15:34
@amilajack I am getting the manifest.json failed message also, but I see the same behavior in the master 0.11.1 on package also so I assume it's okay, but figured I'd mention since I'm having similar problems with packaging.

**Comment by amilajack** [comment] 2017-04-26 15:34
> DEBUG_PROD=true npm run start is essentially the same thing except it won't package it into any exe files, is that right?

The `DEBUG_PROD` env variable is set when building the main process with webpack. So can add `DEBUG_PROD` to any any npm script that builds the main process. This includes the `build-main`, `build`, and `package` scripts.

**Comment by musyilmaz** [comment] 2017-04-26 16:09
@amilajack do you have an eta for update.md?

**Comment by amilajack** [comment] 2017-04-26 18:05
I will release an upgrade guide for every single release. The migration process from `v0.10.0` to `v0.11.0` is going to be difficult (depending on when you cloned the boilerplate) because there are so many breaking changes. I'm not 100% sure if I will release a migration guide for previous releases for that reason. Hopefully someone in the community can contribute this if I dont get around to doing this.

**Comment by musyilmaz** [comment] 2017-04-26 18:37
Like, I am still using react-router 3, I know everything will fail and I am really quite afraid of it :( 

Is not the package-win working before 0.11??? Like maybe even DEBUG_PROD=true????

**Comment by Slapbox** [comment] 2017-04-26 19:12
@musyilmaz upgrading routers is definitely a pain, but shouldn't be a nightmare. I would expect you'll spend a full day's work upgrading though if you rely on routing heavily. I don't rely on routing and obviously there are growing pains on major updates like that.

It's better to just get through the upgrade though as painful as it may be. It's much worse if you put it off for a year, expanding you project and expanding the list of changes that will be needed to get up to speed with the boilerplate.

**Short of upgrading, try this:**

Find the following in your `main.development.js` and comment out the `if` statement that wraps it

```
  mainWindow.webContents.on('context-menu', (e, props) => {
    const { x, y } = props;

    Menu.buildFromTemplate([{
      label: 'Inspect element',
      click() {
        mainWindow.inspectElement(x, y);
      }
    }]).popup(mainWindow);
  });
```
This should let you right click and inspect in your packaged application (there may be some other change needed that I'm forgetting so if not let me know)

This way you can hopefully determine the exact cause of the error in the console.

**Comment by pavel06081991** [comment] 2017-05-06 12:03
@amilajack, I am getting the manifest.json failed message also

**Comment by amilajack** [comment] 2017-05-06 14:21
@Slapbox how did you fix the issue @pavel06081991 is experiencing?

**Comment by jonathanagosto** [comment] 2017-07-06 19:58
Hi,

I am also experiencing the same problem with the `manifest.json` error message.

**Comment by duke79** [comment] 2020-11-11 16:42
Was facing the issue, turns out `window.loadURL` was silently failing because `path` was undefined.
