### ISSUE TITLE
Live reload loads old content

### ISSUE THREAD

**Issue by williamoliveira** [chentsulin/electron-react-boilerplate#909] opened 2017-04-12 13:17 UTC
When it does full page reload it loads with the old version
I dont know how to explain it better so I made a quick video to demonstrate: https://youtu.be/xk-4Q0YAIlw

**Comment by amilajack** [comment] 2017-04-12 16:36
Interesting. Also thanks for the recording. Makes it so much easier for me to see what's going on on your end. If you haven't change anything in the boilerplate after cloning it, it may be because your dependencies are outdated or mismatching. Using yarn will most likely fix this kind of issue:

```
git pull --all
npm i -g yarn
rm -rf node_modules
yarn
```

**Comment by williamoliveira** [comment] 2017-04-12 22:24
Did not fix
It is a clean clone and I was already using yarn

**Comment by amilajack** [comment] 2017-04-12 23:45
try cleaning the yarn cache
```
yarn cache clean
```

and then repeat the previous steps

**Comment by aemxdp** [comment] 2017-04-13 04:35
Same issue for me. Started using `electron-react-boilerplate` few hours ago.

**Comment by williamoliveira** [comment] 2017-04-13 05:25
Cleaned yarn cache, the problem persists

**Comment by Slapbox** [comment] 2017-04-13 18:32
Are you using any node native modules? An example would be `electron-spellchecker`

This module may have been the cause of some issues I've had, but I cannot confirm this is the cause yet.

**Comment by anthonyraymond** [comment] 2017-04-13 22:37
I'm also afected since i rebased from #856 to #898. It may be related to DLL config, since i also often encounter #905 on reload

**Comment by Slapbox** [comment] 2017-04-14 00:07
@anthonyraymond See my comments on #905. I will continue to update based on my findings.

**Comment by amilajack** [comment] 2017-04-14 22:35
Would be great if everyone here could test out https://github.com/chentsulin/electron-react-boilerplate/pull/914

**Comment by williamoliveira** [comment] 2017-04-14 23:15
No luck
But it seems to fix #905 that I was having too sometimes

**Comment by amilajack** [comment] 2017-04-14 23:30
@williamoliveira thats the proper solution for this. Would be great if you could PR to use HtmlWebpackPlugin instead. I don't have much time on my hands this week

**Comment by williamoliveira** [comment] 2017-04-14 23:41
I will try

**Comment by williamoliveira** [comment] 2017-04-15 03:03
I managed to get HtmlWebpackPlugin working, I will do some more manual testing and PR it after
But unfortunately it did not fix this issue :/

**Comment by amilajack** [comment] 2017-04-17 13:02
Can someone please confirm that https://github.com/chentsulin/electron-react-boilerplate/pull/916 resolves the race condition issue? I am not experiencing the race condition issue myself so its impossible to me to test this

**Comment by williamoliveira** [comment] 2017-04-17 14:04
It did not, but fixes #905 at least

**Comment by uppe-r** [comment] 2017-04-17 14:07
Didn't for me as well, can't comment on #905 though since I rarely got that error.

**Comment by amilajack** [comment] 2017-04-17 14:20
Try commenting the `webpack.config.renderer.dev.js` and removing the [dynamic script injection code](https://github.com/chentsulin/electron-react-boilerplate/blob/master/app/app.html#L21-L27). I'm almost certain this will work.

**Comment by williamoliveira** [comment] 2017-04-17 14:37
Was just going to test this when you commented, but didn't work

I noticed that if I reload the page manually a second after it auto reloads it comes with the new bundle.js, it is as if webpack-dev-server is not waiting for the bundle.js to be written before reloading the page

**Comment by uppe-r** [comment] 2017-04-17 14:38
Didn't work for me as well, can confirm what william is saying.

**Comment by amilajack** [comment] 2017-04-17 14:38
If you commented the script injection for the dll, it shouldnt be loading it. Maybe its the cache?

**Comment by williamoliveira** [comment] 2017-04-17 14:46
If you disable the dll plugin the all the vendor gets rendered to bundle.js, works as normal, but the problem continues, it loads the old bundle.js on auto reload

**Comment by williamoliveira** [comment] 2017-04-17 15:06
Found something, removing `multiStep: true` from HotModuleReplacementPlugin fixed it
What is it for? didnt noticed any side effects yet

**Comment by uppe-r** [comment] 2017-04-17 15:12
Can confirm it's working after removing it as @williamoliveira suggested. After a quick search on google about HMR and multistep, it looked like Webpack 2 doesn't go very well with multistep...

**Comment by uppe-r** [comment] 2017-04-17 15:31
#920

**Comment by uppe-r** [comment] 2017-04-17 15:36
[PR](https://github.com/chentsulin/electron-react-boilerplate/pull/920)

**Comment by amilajack** [comment] 2017-04-17 16:45
`multiStep` allows webpack to add incremental hot reloading in multiple passes. Better for larger projects. Shouldn't make much of a difference for most projects.

**Comment by amilajack** [comment] 2017-04-17 16:52
@uppe-r @williamoliveira I have merged both of the PR's you guys have made into the `dev-master` branch of this repo. That way we can test both of your changes.

**Closed** 2017-04-20 06:00 UTC
Labels: waiting-for-response
