### ISSUE TITLE
npm run cleanup leaves orphan code

### ISSUE THREAD

**Issue by Shawry** [chentsulin/electron-react-boilerplate#664] opened 2017-01-20 14:02 UTC
`npm run cleanup` removes app/reducers/counter.js but leaves some code that references it: 
`import type { counterStateType } from '../reducers/counter';` 

This is found in both app/store/configureStore.development.js & app/store/configureStore.production.js. 

There are multiple references to `counterStateType` that need to be removed within those files. This results in a module not found error when running `npm run dev`.

**Comment by amilajack** [comment] 2017-01-20 21:14
pint @tstringer

**Comment by tstringer** [comment] 2017-01-20 21:19
Thanks for the ping, @amilajack. I'll dive into this.

**Comment by tstringer** [comment] 2017-01-22 15:09
@amilajack the PR has been created to resolve this issue. Thanks, @Shawry, for uncovering this! :smile: :+1:

**Comment by amilajack** [comment] 2017-01-23 05:06
@Shawry The PR to fix this was merged. Check if it works for you now with the following

```
npm i -g yarn
git clone https://github.com/chentsulin/electron-react-boilerplate.git
cd electron-react-boilerplate
rm yarn.lock
yarn
yarn run dev
```

**Comment by DrShpongle** [comment] 2017-01-23 09:31
there is an error thrown after merge:
http://take.ms/FmXE2

Bundle is valid though:
http://take.ms/j78eH

**Comment by tstringer** [comment] 2017-01-23 10:53
@DrShpongle I'm not able to reproduce that same error. Plus, if there was a syntax error then the bundle would be invalid.

Can you retry the steps @amilajack post above to verify this issue on your machine?

**Comment by DrShpongle** [comment] 2017-01-23 11:00
@tstringer  Yes, I did clean set up. Let me try to do it again and check.

**Comment by DrShpongle** [comment] 2017-01-23 11:03
Yes, still the same error. Clean set up, master branch.

**Comment by tstringer** [comment] 2017-01-23 11:04
@DrShpongle can you please send me the steps to repro?

**Comment by DrShpongle** [comment] 2017-01-23 11:05
```
git clone https://github.com/chentsulin/electron-react-boilerplate.git
cd electron-react-boilerplate
rm yarn.lock
yarn
yarn run dev
```

**Comment by DrShpongle** [comment] 2017-01-23 11:06
macOS Sierra

**Comment by tstringer** [comment] 2017-01-23 11:10
So you're saying you aren't even running `yarn run cleanup`? Wow that's even more interesting. Running those exact steps, I have no issues. The sample app shows up error-free.

Perhaps dig into `bundle.js` and see what jumps out at you?

I'm on my Linux machine right now, I can try it on macOS later but I wouldn't expect my outcome to change.

**Comment by DrShpongle** [comment] 2017-01-23 11:16
If it could help - I got this error when `npm start`
http://take.ms/5XrtF

**Comment by DrShpongle** [comment] 2017-01-23 12:35
Ah, I'm so sorry, man - my :3000 port was occupied by another app.
![giphy](https://cloud.githubusercontent.com/assets/1519448/22204162/37718958-e179-11e6-8b8f-d1e0422d55aa.gif)

**Closed** 2017-01-23 18:58 UTC

**Comment by tstringer** [comment] 2017-01-23 20:02
@DrShpongle no problem at all 😄  just glad you got it worked out.
