### ISSUE TITLE
Cannot run build

### ISSUE THREAD

**Issue by SaraVieira** [chentsulin/electron-react-boilerplate#1036] opened 2017-06-04 21:53 UTC
Hello,

Great boilerplate , I do get an error when trying to run the build:

Here is the stack trace:

```
[0] ERROR in ./~/fsevents/~/rc/index.js
[0] Module parse failed: /Users/saravieira/Desktop/electron-workshop/node_modules/fsevents/node_modules/rc/index.js Unexpected character '#' (1:0)
[0] You may need an appropriate loader to handle this file type.
[0] | #! /usr/bin/env node
[0] | var cc   = require('./lib/utils')
[0] | var join = require('path').join
[0]  @ ./~/fsevents/~/node-pre-gyp/lib/info.js 11:13-26
[0]  @ ./~/fsevents/~/node-pre-gyp/lib ^\.\/.*$
[0]  @ ./~/fsevents/~/node-pre-gyp/lib/node-pre-gyp.js
[0]  @ ./~/fsevents/fsevents.js
[0]  @ ./~/chokidar/lib/fsevents-handler.js
[0]  @ ./~/chokidar/index.js
[0]  @ ./~/electron-reload/main.js
[0]  @ ./app/main.dev.js
[0]  @ multi babel-polyfill ./app/main.dev
[0] 
[0] ERROR in unknown: Invalid number (230534:27)
[0] npm
[0]  ERR! code ELIFECYCLE
[0] npm ERR! errno 2
[0] npm ERR!
[0]  electron-workshop@1.0.2 build-main: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors`
[0] npm ERR! Exit status 2
[0] npm ERR! 
[0] npm ERR!
[0]  Failed at the dagger@1.0.2 build-main script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Has this happened to anyone ?
In dev this run awesome

**Comment by amilajack** [comment] 2017-06-04 21:59
Interesting. How did you install you dependencies? I would recommend using yarn:
```bash
npm i -g yarn
rm -rf node_modules
yarn
```

**Comment by SaraVieira** [comment] 2017-06-04 23:14
I have used yarn and I am using the latest version of node. 

I made some changes, you can check the repo at:https://github.com/SaraVieira/Dagger

It may have been a newbie mistake

**Comment by amilajack** [comment] 2017-06-04 23:16
@SaraVieira Try doing a fresh clone of the boilerplate. If there its no issue with running `npm run build`/`yarn build` with the fresh clone, we know that the issue is with your fork. This helps narrow down the issue.

**Comment by crakjie** [comment] 2017-06-12 14:36
@amilajack I have almost the same problem than @SaraVieira, 
Do you have an idea to make this ` ERROR in unknown: Invalid number (76705:15)` more verbose?

**Comment by amilajack** [comment] 2017-06-12 18:56
@SaraVieira try some of the solution here: https://github.com/webpack/webpack/issues/4603#issuecomment-290914588

**Comment by amilajack** [comment] 2017-06-12 18:57
@crakjie Are you getting an error that includes `Unexpected character '#' `?

**Comment by crakjie** [comment] 2017-06-12 20:54
I think the # problem in the first message is not related to `ERROR in unknown: Invalid number (230534:27)` In my case, the message come alone.

**Comment by amilajack** [comment] 2017-06-12 21:00
@crakjie what does your stacktrace look like?

**Comment by amilajack** [comment] 2017-06-12 22:58
@SaraVieira you can resolve this by adding `fsevents` to your `externals` in the base webpack config. If `fsevents` is required in the renderer process then move the dependency that requires it to `./app/package.json`

**Comment by crakjie** [comment] 2017-06-13 09:58
@amilajack In the log file I have the same stack trace than in #967, which just mean "something want wrong" I think.

**Comment by amilajack** [comment] 2017-06-27 02:06
After looking at this again, this most likely has to do with `fsevents` being a native module. There's two possible solutions to this:

1. Add the [shebang-loader](https://github.com/JavascriptIsMagic/shebang-loader) to your `webpack.config.base.js`

2. Add `fsevents` as an external webpack dependency. In `webpack.config.base.js`
```js
export default {
  externals: [
    'fsevents',
    ...Object.keys(externals || {})
  ],
  // ...
}
```

**Comment by amilajack** [comment] 2017-06-27 02:13
Closing because I think this was addressed. Please let me know if you're still experiencing issues with this and I will gladly reopen the issue

**Closed by amilajack** 2017-06-27 02:13 UTC
Labels: waiting-for-response

**Comment by shankar2105** [comment] 2017-09-06 10:12
```
[./app/actions/action_types.js] ./app/actions/action_types.js 538 bytes {0} [built]
[1] [./app/actions/authorisation.js] ./app/actions/authorisation.js 1.29 kB {0} [built]
[1] [./app/containers/Root.js] ./app/containers/Root.js 1.66 kB {0} [built]
[1] [./app/imgs/new-public-id.svg] ./app/imgs/new-public-id.svg 645 bytes {0} [built]
[1] [./app/imgs/new-website.svg] ./app/imgs/new-website.svg 1.15 kB {0} [built]
[1] [./app/index.js] ./app/index.js 2
[1] .8 kB {0} [built]
[1] [./app/lib/api.js] ./app/lib/api.js 16.7 kB {0} [built]
[1] [./app/lib/temp.js] ./app/lib/temp.js 683 bytes {0} [built]
[1] [./app/locales/en.js] ./app/locales/en.js 4.8 kB {0} [built]
[1] [./app/locales/loader.js] ./app/locales/loader.js 533 bytes {0} [built]
[1] [./app/routes.js] ./app/routes.js 1.97 kB {0} [built]
[1] [./app/store/configureStore.js] ./app/store/configureStore.js 251 bytes {0} [built]
[1] [./app/store/configureStore.prod.js] ./app/store/configureStore.prod.js 1.09 kB {0} [built]
[1] [./app/stylus/main.styl] ./app/stylus/main.styl 1.14 kB {0} [built]
[1] [./node_modules/css-loader/index.js!./node_modules/stylus-loader/index.js!./app/stylus/main.styl] ./node_modules/css-loader!./node_modules/stylus-loader!./app/stylus/main.styl 24.6 kB {0} [built]
[1]     + 521 hidden modules
[1]
[1] ERROR in unknown: Invalid number (68467:20)
[1]
[1] npm
[1]  ERR! Darwin 16.5.0
[1] npm ERR! argv "/Users/shankar/.nvm/versions/node/v7.9.0/bin/node" "/Users/shankar/.nvm/versions/node/v7.9.0/bin/npm" "run" "build-renderer"
[1] npm
[1] ERR! node v7.9.0
[1] npm ERR! npm  v4.2.0
[1] npm ERR!
[1] code ELIFECYCLE
[1] npm ERR! errno 2
[1] npm ERR!
[1]  web-hosting-manager@0.2.0 build-renderer: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors`
[1] npm ERR! Exit status 2
[1] npm
[1] ERR!
[1] npm ERR! Failed at the web-hosting-manager@0.2.0 build-renderer script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the web-hosting-manager package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs web-hosting-manager
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls web-hosting-manager
[1] npm ERR!
[1]  There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/shankar/.npm/_logs/2017-09-06T10_07_41_449Z-debug.log
[1] npm run build-renderer exited with code 2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@amilajack I get the same error `ERROR in unknown: Invalid number (68467:20)` even after adding [this](https://github.com/chentsulin/electron-react-boilerplate/issues/1036#issuecomment-311232017)

**Comment by matthewcc** [comment] 2017-10-20 21:37
I realize this issue is closed, but I was getting the cryptic `Invalid number` error and the above solutions did not help me, and I spent a large amount of time trying to fix it. A variety of (relatively old and abandoned) modules I was importing would trigger this error, and after digging into those modules own dependencies and importing them directly, the `Invalid number` error actually came with some useful information:

```
if (typeof mode === 'function' || typeof mode === 'undefined') {
    callback = mode;
    mode = 0777 & (~process.umask());
           ^
}

 if (!callback) {

```
This came from the module `mkpath`. It turns out this is a deprecated way of writing an octal number in node, and babel will only accept the es6 way of (using the example) `0o777`. So, at least in my case this error ended up having nothing to do with this boilerplate (which is great, thank you!), and I was able to solve the issue by adding a loader to the base config: [octal-number-loader](https://github.com/jonwoodring/octal-number-loader)

**Comment by shhdharmen** [comment] 2017-11-14 11:49
@matthewcc I tried with octal-number-loader, but still getting the same error. Any idea why? Below is my webpack.config.js file
`var webpack = require('webpack');
const config = {
    entry: ['babel-polyfill', './src/main/index.js', ...],
    plugins: [
        new webpack.DefinePlugin({ "global.GENTLY": false })
    ],
    node: {
        __dirname: true,
    },
    resolve: {
        alias: {
            'inherits': 'inherits/inherits_browser.js',
            'superagent': 'superagent/lib/client',
            'emitter': 'component-emitter',
        }
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /(node_modules|bower_components)/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['@babel/preset-env']
                }
            }
        }, {
            test: /tar[\\\/].*\.js$/,
            loader: 'babel-loader!octal-number-loader'
        }]
    }
};

module.exports = config;`

**Comment by iamblue** [comment] 2017-12-12 08:56
same issue +1

**Comment by amilajack** [comment] 2017-12-12 16:54
@iamblue please share your stack trace

**Comment by chengmu** [comment] 2018-01-08 04:07
> @matthewcc save my day!!  

 ERROR in unknown： Invalid number； google to this issue,   same  module  mkpath

**Comment by matthewcc** [comment] 2018-01-25 21:11
@shhdharmen sorry for the long delay I missed this. Hopefully, you found the answer.

I don't really know the ins and outs of webpack, but my own module setting looks like this:
`    {
      test: /\.js$/,
      loader: 'octal-number-loader'
    }`

You may not want/need to run it through babel. I also can only barely comprehend regex, but its possible your test is also filtering out the files you wanted to convert.

**Comment by albertotorresfoltyn** [comment] 2018-04-26 16:36
same here... my stack

WARNING in ./node_modules/electron-debug/index.js
84:85-106 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

ERROR in ./node_modules/npm/bin/npm-cli.js
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| #!/usr/bin/env node
| ;(function () { // wrapper in case we're in module_context mode
|   // windows: running "npm blah" in this folder will invoke WSH, not node.
 @ ./node_modules/npm/lib/npm.js 470:4-32
 @ dll renderer
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cmfl@0.13.2 build-dll: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the cmfl@0.13.2 build-dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alberto\AppData\Roaming\npm-cache\_logs\2018-04-26T16_10_50_220Z-debug.lognpm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cmfl@0.13.2 postinstall: `node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the cmfl@0.13.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     C:\Users\Alberto\AppData\Roaming\npm-cache\_logs\2018-04-26T16_10_50_845Z-debug.log

**Comment by githoniel** [comment] 2018-12-11 01:03
matthewcc  is right ! Greate thank for your valuable invesgate !
