### ISSUE TITLE
Test suite does not resolve electron global requires.

### ISSUE THREAD

**Issue by tmoitie** [chentsulin/electron-react-boilerplate#215] opened 2016-05-09 11:24 UTC
If I do `import { remote } from 'electron';` within the app, and allow that component to be tested, the test suite throws an error:

```Error: /electron-react-boilerplate/app/components/Home.js: Can't resolve 'electron' in '/electron-react-boilerplate/app/components'```

Full error is here, if useful: https://gist.github.com/tmoitie/c9bd7ac88c76c344a69cf615ff229cd8

A branch with the failing test is here: https://github.com/tmoitie/electron-react-boilerplate (diff is https://github.com/tmoitie/electron-react-boilerplate/commit/72042b185b2e18e53e6baaa6c46108ad2c117668)

The code runs as expected in electron, but not the test suite.

I have attempted to adjust the config in `webpack.config.node.js` to add `target: 'electron-renderer'`, and I attempted to run the tests using `electron-mocha` all to no avail. Has anyone successfully managed to run test suites with connections to the parent process?

**Comment by chentsulin** [comment] 2016-05-13 17:43
duplicate of #204, we can keep discuss there.

**Closed by chentsulin** 2016-05-13 17:43 UTC
