### ISSUE TITLE
After Packaging on first launch error occurring !!

### ISSUE THREAD

**Issue by pikvik** [chentsulin/electron-react-boilerplate#1437] opened 2018-02-23 04:44 UTC
have made an anti virus electron app . All runs smoothly and fine in dev. But after packaging and installing on first launch attached error pops up. Error Pop up is below . After okaying the error it runs fine. 
![screen shot 2018-02-22 at 7 12 56 pm](https://user-images.githubusercontent.com/18361946/36578297-37a9a5b8-1882-11e8-99eb-056fe258c37d.png)

**Comment by amilajack** [comment] 2018-02-23 04:45
Dupe of https://github.com/chentsulin/electron-react-boilerplate/issues/306

**Closed by amilajack** 2018-02-23 04:45 UTC

**Comment by pikvik** [comment] 2018-02-23 05:33
I'm sorry but I don't understand how its a dupe of the issue you mentioned. Cuz I dont think theres a virus in my repo. I'm relatively new to electron. Any help on how I could stop the error from occurring would be really really appreciated.

**Comment by amilajack** [comment] 2018-02-23 05:35
See this: https://github.com/electron/spectron/issues/93
