### ISSUE TITLE
Failed to read content scripts

### ISSUE THREAD

**Issue by mmick66** [chentsulin/electron-react-boilerplate#1381] opened 2018-01-16 12:39 UTC
I follow the instructions and run `npm run dev`. I get an error on the console, although the app runs in its window.

```
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/michailidis/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/michailidis/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/michailidis/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/Users/michailidis/Programs/react-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/michailidis/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
2018-01-16 13:36:13.494 Electron Helper[12512:16130705] Couldn't set selectedTextBackgroundColor from default ()
```

**Comment by amilajack** [comment] 2018-02-01 06:09
Dupe of https://github.com/chentsulin/electron-react-boilerplate/issues/1383

**Closed by amilajack** 2018-02-01 06:09 UTC
