### ISSUE TITLE
install-app-deps in postinstall script fails on Linux

### ISSUE THREAD

**Issue by KPrabs106** [chentsulin/electron-react-boilerplate#896] opened 2017-04-03 17:53 UTC
System is running: 
- Linux 4.4.50-v7+
- Node v7.8.0
- NPM v4.2.0

When I run npm install, it fails at ``concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"``
It looks like ``install-app-deps`` is causing the trouble. Here's the output:

> \> concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
[0] Options:
[0]   --platform            [choices: "linux", "darwin", "win32"] [default: "linux"]
[0]   --arch                        [choices: "ia32", "x64", "all"] [default: "arm"]
[0] 
[0] Invalid values:
[0]   Argument: arch, Given: "arm", Choices: "ia32", "x64", "all"
[0] install-app-deps exited with code 1
[1] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0

Could anyone help me with this issue? It seems to run fine on my Windows machine.

**Comment by amilajack** [comment] 2017-04-03 18:05
Edit the `package-linux` script to this:
```
"package-linux": "npm run build && build --linux --arch all",
```

And then run `npm run package-linux`. What is the output of that?

**Comment by KPrabs106** [comment] 2017-04-03 18:22
It errors out: 

>Error: --arch cannot be used if --linux is passed
    at processTargets (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/builder.js:147:19)
    at normalizeOptions (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/builder.js:199:9)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/builder.js:22:25
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

**Comment by amilajack** [comment] 2017-04-03 18:39
Hmm. Try this:
```
"package-linux": "npm run build && build --arch all",
```

and repeat

**Comment by KPrabs106** [comment] 2017-04-03 20:11
More errors:

>Unhandled rejection Error: spawn /home/pi/Documents/Electron Projects/Application/node_modules/7zip-bin-linux/arm/7za ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at spawn (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/src/util.ts:97:3)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/src/binDownload.ts:56:3
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at doGetBin (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/out/binDownload.js:55:21)
    at getBin (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/src/binDownload.ts:24:38)
    at Object.<anonymous> (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/targets/appImage.ts:18:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at targetClass (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/linuxPackager.ts:45:20)
    at LinuxPackager.createTargets (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/linuxPackager.ts:42:96)
    at createTargets (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/targets/targetFactory.ts:22:12)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/packager.ts:231:41
From previous event:
    at Packager.doBuild (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/packager.js:351:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/packager.ts:159:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/packager.js:257:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/builder.ts:217:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
Downloading tmp-8054-0-electron-v1.6.5-linux-x64.zip
[=======>                                     ] 19.3% of 48.76 MB (1.02 MB/s)
Unhandled rejection Error: spawn /home/pi/Documents/Electron Projects/Application/node_modules/7zip-bin-linux/arm/7za ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at spawn (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/src/util.ts:97:3)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/src/binDownload.ts:56:3
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at doGetBin (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/out/binDownload.js:55:21)
    at getBin (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/src/binDownload.ts:24:38)
    at downloadFpm (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/targets/fpm.ts:26:10)
    at Object.<anonymous> (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/targets/fpm.ts:16:36)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at targetClass (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/linuxPackager.ts:55:20)
    at LinuxPackager.createTargets (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/linuxPackager.ts:42:96)
    at createTargets (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/targets/targetFactory.ts:22:12)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/packager.ts:231:41
From previous event:
    at Packager.doBuild (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/packager.js:351:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/packager.ts:159:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/packager.js:257:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/builder.ts:217:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
Downloading tmp-8054-1-SHASUMS256.txt-1.6.5
[============================================>] 100.0% of 2.85 kB (2.85 kB/s)
Error: spawn /home/pi/Documents/Electron Projects/Application/node_modules/7zip-bin-linux/arm/7za ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at spawn (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder-util/src/util.ts:97:3)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/packager/dirPackager.ts:43:11
    at Generator.next (<anonymous>)
    at checker.validate.then (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/node_modules/electron-download-tf/build/index.js:251:7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From previous event:
    at unpackElectron (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/packager/dirPackager.js:38:21)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/platformPackager.ts:143:9
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at LinuxPackager.doPack (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/platformPackager.js:267:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/platformPackager.ts:98:16
    at Generator.next (<anonymous>)
From previous event:
    at LinuxPackager.pack (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/platformPackager.js:160:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/packager.ts:231:22
From previous event:
    at Packager.doBuild (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/packager.js:351:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/packager.ts:159:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/packager.js:257:11)
    at /home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/src/builder.ts:217:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/pi/Documents/Electron Projects/Application/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

**Comment by amilajack** [comment] 2017-04-03 20:14
I doubt that this is an issue with the boilerplate. `npm run build` is actually part of our test suite and that script is tested on linux as part of our CI setup with travis. Try running `npm run package` with a fresh clone of the boilerplate and let me know if that works.

**Comment by KPrabs106** [comment] 2017-04-03 20:33
It's giving the same error. Looks like it's happening because of the arch argument.

[1] Options:
[1]   --platform            [choices: "linux", "darwin", "win32"] [default: "linux"]
[1]   --arch                        [choices: "ia32", "x64", "all"] [default: "arm"]
[1] 
[1] Invalid values:
[1]   Argument: arch, Given: "arm", Choices: "ia32", "x64", "all"
[1] install-app-deps exited with code 1
[2] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0

Any ideas on how to change the arch, at least for the install-app-deps part?

**Comment by amilajack** [comment] 2017-04-03 20:47
Are you using a fresh, unchanged clone of the repo?

**Comment by KPrabs106** [comment] 2017-04-03 20:48
Yes I am

**Comment by amilajack** [comment] 2017-04-03 20:50
Not sure what the issue is. Try 3 of #400. May be a cache issue. Try using yarn as well.
```
rm -rf node_modules
npm i -g yarn
yarn
```

**Comment by amilajack** [comment] 2017-04-04 03:21
Closing because I think this is an issue with electron-builder

**Closed by amilajack** 2017-04-04 03:21 UTC
Labels: question, waiting-for-response

**Comment by KPrabs106** [comment] 2017-04-09 06:09
Yes, you're right, it's an electron-builder problem. It turns out that it doesn't support the ARM architecture that the Raspberry Pi uses. Is there any way I can remove electron-builder from this? Even "npm run dev" results in nothing showing up.

When I tested a barebones Electron app, it seemed to run fine, so I'm hoping if I get rid of electron-builder, everything should run fine.

**Comment by amilajack** [comment] 2017-04-09 15:40
I think the default should work. The boilerplate uses AppImage by default. According to this comment, [AppImage should work on the pi](https://github.com/electron-userland/electron-builder/issues/778#issuecomment-249429528)

**Comment by KPrabs106** [comment] 2017-04-09 16:30
Yeah I'm getting some ENEONT error while packaging. I started an issue on their page, so hopefully someone might be able to help me out.

**Comment by KPrabs106** [comment] 2017-04-10 04:09
Just in case anyone else with the same problem stumbles across this:
My workaround is to just build it, with `npm run build`. Then I downloaded the armv7l binaries for electron from here: https://github.com/electron/electron/releases
Then I just package it manually, by copying over the app folder to the resources folder inside the prebuilt electron binaries.

**Comment by njho** [comment] 2019-02-19 03:16
@KPrabs106 

Could you break that process down a couple steps? I'm thinking I'll need to do the same thing on my end.

Cheers
