### ISSUE TITLE
Very high cpu requirement for development

### ISSUE THREAD

**Issue by nikhilag** [chentsulin/electron-react-boilerplate#1110] opened 2017-06-29 16:06 UTC
In my case, the dev application is taking up 33% cpu approx which is extraordinarily high! Has anyone else seen this issue? How can I find out what's going on here?

**Comment by amilajack** [comment] 2017-06-29 18:23
I've noticed this as well. Might be that webpack is doing some unnecessary work. Not sure at the moment.

**Comment by amilajack** [comment] 2017-06-29 20:38
Duplicate of https://github.com/chentsulin/electron-react-boilerplate/issues/1110. Let's merge this into that discussion.

**Closed by amilajack** 2017-06-29 20:38 UTC

**Comment by nikhilag** [comment] 2017-06-30 01:31
This issue is #1110. Kindly update the number of original issue here.

**Comment by amilajack** [comment] 2017-06-30 03:05
Fixed
