### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by oussamajabnouni** [chentsulin/electron-react-boilerplate#1402] opened 2018-01-31 14:18 UTC
Node > v8.9.4
Npm > 5.6.0
Yarn > 1.3.2

After fresh install i got this error

yarn 
```
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
child_process.js:644
    throw err;
    ^
Error: Command failed: npm ls node-sass weak --json
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at __dirname (C:/shop/internals/scripts/CheckNativeDep.js:18:41)
    at Object.<anonymous> (C:/shop/internals/scripts/CheckNativeDep.js:7:1)
    at Module._compile (module.js:643:30)
    at loader (C:\shop\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\shop\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
error Command failed with exit code 1
```

npm

```
WARNING in ./node_modules/formidable/lib/incoming_form.js
1:43-50 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/formidable/lib/incoming_form.js
 @ ./node_modules/formidable/lib/index.js
 @ ./node_modules/superagent/lib/node/index.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
81:45-58 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
84:85-106 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

ERROR in dll renderer
Module not found: Error: Can't resolve 'react-scripts' in 'C:\shop'
 @ dll renderer

ERROR in ./node_modules/bulma/bulma.sass
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset "utf-8"
| /*! bulma.io v0.6.2 | MIT License | github.com/jgthms/bulma */
| @import "sass/utilities/_all"
 @ dll renderer
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! electron-react-boilerplate@0.13.1 build-dll: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.13.1 build-dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Café Berber\AppData\Roaming\npm-cache\_logs\2018-01-31T15_10_49_471Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! electron-react-boilerplate@0.13.1 postinstall: `node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by asmallfurrywombat** [comment] 2018-01-31 19:02
I was able to work around it by removing the "node -r babel-register internals/scripts/CheckNativeDep.js && " from the postinstall entry in the package.json scripts.

**Comment by amilajack** [comment] 2018-01-31 21:29
I am not able to reproduce this. I am on `yarn@1.3.2`, latest erb version, `node@9.4.0`, 'npm@5.6.0'

**Comment by ziedhajsalah** [comment] 2018-01-31 22:19
Same issue for me with `node@9.3.0` and `yarn@1.3.2` and `npm@5.6.0`.
The solution of @asmallfurrywombat solved my problem.

**Comment by amilajack** [comment] 2018-02-01 06:02
Pushed `v0.13.2` to fix this. Please try a fresh clone and see if it works

**Comment by ziedhajsalah** [comment] 2018-02-01 08:28
@amilajack that's fine for me thank you.
And to fix the second issue of @oussamajabnouni we have to handle processing `.sass` (actually, we have only `.scss`) files in the webpack config and it will work.

**Comment by amilajack** [comment] 2018-02-01 17:17
That's correct. I'll try to push a fix for this soon

**Closed** 2018-10-01 18:16 UTC
Labels: PR
