### ISSUE TITLE
React router redirection doesn't work

### ISSUE THREAD

**Issue by erick2014** [chentsulin/electron-react-boilerplate#955] opened 2017-04-27 03:37 UTC
I can't perform a redirection using react router, I have added a button which calls history.push, but it doesn't work 

![router-issue1](https://cloud.githubusercontent.com/assets/7244087/25466982/4de92726-2ad1-11e7-8506-42fd189cde71.png)

![router-issue2](https://cloud.githubusercontent.com/assets/7244087/25466969/3f949f5c-2ad1-11e7-9a6e-193f6fdf0bc4.png)

I have checked this PR:
https://github.com/chentsulin/electron-react-boilerplate/pull/949

But I still not able to redirect to another page, even using the example from the starter kit

**Comment by anthonyraymond** [comment] 2017-04-27 11:43
Hi @erick2014 the #949 has been merged in `dev-master` branch (not in `master` yet, the fix will most likely come out with 0.11.2.

To fix this, you can rebase `dev-master` until 0.11.2 come out.

**Comment by erick2014** [comment] 2017-04-27 14:49
@anthonyraymond I actually had tested your changes but I was missing a small part, I didn't realize you had removed the Router component from routes.js file, so I had this:

```
 <Router>
    <App>
      <Switch>
        <Route path="/" component={LoginPage} />
        <Route path="/home" component={HomePage} />
      </Switch>
    </App>
  </Router>
```
Instead of this:
```
<App>
      <Switch>
        <Route path="/" component={LoginPage} />
        <Route path="/home" component={HomePage} />
      </Switch>
    </App>
```
Thx for your help @anthonyraymond

**Comment by anthonyraymond** [comment] 2017-04-27 14:50
No problem ;)

**Comment by erick2014** [comment] 2017-04-27 15:12
The only weird thing that I found when moving the router paths was this:

http://screencast-o-matic.com/watch/cbfto1XoJU

the app got in blank and you have to close it and open it again

**Comment by anthonyraymond** [comment] 2017-04-27 22:11
It it only happening when changing `router.js`?

**Comment by erick2014** [comment] 2017-04-28 16:01
@anthonyraymond in routes.js file, and if u refresh the page you also get a blank page

**Comment by anthonyraymond** [comment] 2017-04-28 16:03
@erick2014 if you don't change the `route.js`, but reload the UI with <kbd>CTRL</kbd><kbd>R</kbd> it bug as well?

**Comment by erick2014** [comment] 2017-04-28 16:11
@anthonyraymond yes man, if I press cmd + r within /home page, I got a blank page, looks like we need a way to tell the router what is its root path: this is my routes file:

    
```
<App>
      <Switch>
        <Route path="/home" component={HomePage} />
        <Route path="/" component={LoginPage} />
      </Switch>
    </App>
```

Also I have noticed if I move the / path to the beginning then I trigger a history.push it will not work

**Comment by anthonyraymond** [comment] 2017-04-28 16:20
@erick2014 IMO the bug comes from your code. I just rebased `dev-master`, and tried out but everything is working.

Did you replace `const router = routerMiddleware(hashHistory);` `const router = routerMiddleware(history);` as in https://github.com/chentsulin/electron-react-boilerplate/pull/949/files#diff-9d94bec4f856963b60e57a808ff00a61R28 ?

**Comment by erick2014** [comment] 2017-04-28 17:01
haha yes man I did it, well I am not sure if the bug is mine, but I am afraid you need a root path there man, because you are changing the page with redux, so if u refresh u will get the location where u were, well I think, I am not sure

**Comment by anthonyraymond** [comment] 2017-04-28 17:08
Sure you need a root path. But you messed up something because the boilerplate work as expected for me

**Comment by erick2014** [comment] 2017-04-28 17:14
@anthonyraymond I didnt change anything from the structure haha

**Comment by anthonyraymond** [comment] 2017-04-28 17:16
One of my project is working, and the boilerplate as well.... But yours is not

**Comment by erick2014** [comment] 2017-04-28 17:20
I'll figure out what to do later, thx any way

**Comment by anthonyraymond** [comment] 2017-04-28 19:50
I finally was able to reproduce. I partially fiex it in #958 (not merged yet).

BUT

having routes defined with `/` first still fail.

Does not work
```
<Switch>
  <Route path="/" component={HomePage} />
  <Route path="/counter" component={CounterPage} />
</Switch>
```

Work
```
<Switch>
    <Route path="/counter" component={CounterPage} />
    <Route path="/" component={HomePage} />
  </Switch>
```

**Comment by erick2014** [comment] 2017-04-28 20:17
@anthonyraymond that is what I was trying to explain you haha, thx

**Comment by amilajack** [comment] 2017-04-29 23:51
Was this fully resolved?

**Comment by anthonyraymond** [comment] 2017-04-30 10:57
Not the path order

**Comment by erick2014** [comment] 2017-05-02 14:19
@amilajack yep, we are waiting for changes in this pr to be in master branch

**Comment by amilajack** [comment] 2017-05-02 14:32
Was merged in `v0.11.2
`

**Comment by erick2014** [comment] 2017-05-02 15:20
@amilajack I was waiting for that merge, I've update to v0.11.2, and now I'm able to perform a redirection to /home page and also I can refresh the page with cmd + r and still working, yujuu, thx for that update!!!

**Comment by amilajack** [comment] 2017-05-02 15:21
Thank @anthonyraymond. He did all the work

**Closed by amilajack** 2017-05-02 15:21 UTC
Labels: waiting-for-response

**Comment by arcanrun** [comment] 2019-04-10 21:08
I think the main problem is in "exact" prop: you should pass it to the component, which has path "/" 

https://reacttraining.com/react-router/web/api/NavLink/exact-bool

otherwise the React router will be confused, because a slash is present in every path ...
