### ISSUE TITLE
Errors thrown from what looks like extension injection?

### ISSUE THREAD

**Issue by mmclau14** [chentsulin/electron-react-boilerplate#1273] opened 2017-10-14 21:43 UTC
it seems like errors are being thrown immediately when the app starts up from what looks like chrome extension paths?

```
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/michaelmclaughlin/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/michaelmclaughlin/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
(node:43950) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/extract-text-webpack-plugin/index.js:271:24
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:3145:5)
    at ExtractTextPlugin.<anonymous> (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/extract-text-webpack-plugin/index.js:268:10)
    at Compilation.applyPluginsAsyncSeries (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/lib/Compilation.js:603:8)
    at applyPluginsParallel.err (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/lib/Compiler.js:508:17)
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
Failed to read content scripts { Error: EACCES: permission denied, open '/Users/michaelmclaughlin/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at readArrayOfFiles (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:235:23)
    at Array.map (native)
    at contentScriptToEntry (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:242:21)
    at Array.map (native)
    at injectContentScripts (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:250:48)
    at loadExtension (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/chrome-extension.js:279:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/michaelmclaughlin/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js' }
2017-10-14 16:40:12.434 Electron Helper[43962:34405816] Couldn't set selectedTextBackgroundColor from default ()
```

**Comment by jhen0409** [comment] 2017-10-21 11:00
Duplicate of #1220. Upgrade `electron-devtools-installer` to `v2.2.1` will resolve the issue.

**Closed by jhen0409** 2017-10-21 11:00 UTC

**Comment by gzgogo** [comment] 2017-11-20 10:06
@jhen0409 i had upgrade electron-devtools-installer to v2.2.1, but still has this issue.

**Comment by jhen0409** [comment] 2017-11-20 10:19
If you still has this issue, please run dev mode with `UPGRADE_EXTENSIONS=1` env, or try delete `<userData path>/extensions` directory and restart app.

**Comment by gzgogo** [comment] 2017-11-20 10:22
@jhen0409 Thanks! I add sudo in front of the dev command to fix this issue. chinese?
